CREATE TABLE site_first_information (
	id VARCHAR (6) NOT NULL,
	NumDots INT NOT NULL,
	SubdomainLevel INT NOT NULL,
	PathLevel INT NOT NULL,
	UrlLength INT NOT NULL,
	NumDash INT NOT NULL,
	NumDashInHostname INT NOT NULL,
	AtSymbol INT NOT NULL,
	TildeSymbol INT NOT NULL,
	NumUnderscore INT NOT NULL,
	NumPercent INT NOT NULL,
	NumQueryComponents INT NOT NULL,
	NumAmpersand INT NOT NULL,
	NumHash INT NOT NULL,
	NumNumericChars INT NOT NULL,
	NoHttps INT NOT NULL,
	RandomString INT NOT NULL,
	IpAddress INT NOT NULL,
	DomainInSubdomains INT NOT NULL,
	DomainInPaths INT NOT NULL,
	HttpsInHostname INT NOT NULL,
	HostnameLength INT NOT NULL,
	PathLength INT NOT NULL,
	QueryLength INT NOT NULL,
	DoubleSlashInPath INT NOT NULL,
	PRIMARY KEY (ID)
);