CREATE TABLE site_second_information (
	ID Varchar (6) NOT NULL,
	NumSensitiveWords INT NOT NULL,
	EmbeddedBrandName INT NOT NULL,
	PctExtHyperlinks FLOAT NOT NULL,
	PctExtResourceUrls FLOAT NOT NULL,
	ExtFavicon INT NOT NULL,
	InsecureForms INT NOT NULL,
	RelativeFormAction INT NOT NULL,
	ExtFormAction INT NOT NULL,
	AbnormalFormAction INT NOT NULL,
	PctNullSelfRedirectHyperlinks FLOAT NOT NULL,
	FrequentDomainNameMismatch INT NOT NULL,
	FakeLinkInStatusBar INT NOT NULL,
	RightClickDisabled INT NOT NULL,
	PopUpWindow INT NOT NULL,
	SubmitInfoToEmail INT NOT NULL,
	IframeOrFrame INT NOT NULL,
	MissingTitle INT NOT NULL, 
	ImagesOnlyInForm INT NOT NULL,
	SubdomainLevelRT INT NOT NULL,
	UrlLengthRT INT NOT NULL,
	PctExtResourceUrlsRT INT NOT NULL,
	AbnormalExtFormActionR INT NOT NULL,
	ExtMetaScriptLinkRT INT NOT NULL,
	PctExtNullSelfRedirectHyperlinksRT INT NOT NULL,
	PRIMARY KEY (ID)
);